#
# Copyright (C) 2021 B3Partners B.V.
#
# SPDX-License-Identifier: MIT
#
openapi: 3.0.3
info:
  title: 'admin-models'
  description: 'Tailormap admin API models'
  version: '1.0'

# no servers or paths, just the models in this document
servers: [ ]
paths: { }

components:
  schemas:
    ServerSentEvent:
      description: 'Server sent event'
      type: object
      properties:
        eventType:
          type: string
          description: 'Type of event'
          enum: [ 'keep-alive', 'entity-created', 'entity-deleted', 'entity-updated' ]
        details:
          type: object

    EntityEvent:
      type: object
      properties:
        entityName:
          type: string
        id:
          type: string
        object:
          description: 'The entity in JSON, only included in created and updated events.'
          type: object

    TaskSchedule:
      type: object
      required:
        - cronExpression
      properties:
        uuid:
          description: 'UUID of the task; this is the unique identifier of the task'
          type: string
          format: uuid
          readOnly: true
          nullable: true
        description:
          description: 'Human-readable description of the task.'
          type: string
          nullable: true
        cronExpression:
          description: 'Cron expression for the task'
          type: string
          nullable: false
        priority:
          description: 'Priority of the task'
          type: integer
          nullable: true
